### ISSUE TITLE
Default Selected Value is still "Nothing selected"

### ISSUE THREAD

**Issue by geck123** [balexbyrd/sense-FieldUI#15] opened 2017-09-08 09:31 UTC
Hi, this is a great extension.  Thanks for contribution.

However, there is an issue with "Default Selected Value".

If I input some values for "Label" in "Dimension" and "Default Selected Value", even after refreshing the page, the default selected value would still be selecting "Nothing selected", not the default selected value I entered.

Could you please take a look and fix this?  Thanks.

**Comment by balexbyrd** [comment] 2018-04-20 21:37
Closing as it's a duplicate of #8

**Closed by balexbyrd** 2018-04-20 21:37 UTC
