### ISSUE TITLE
Default Selected Value

### ISSUE THREAD

**Issue by amrrs** [balexbyrd/sense-FieldUI#14] opened 2017-08-21 10:57 UTC
Hi, Wonderful job with the Extension. But I'm struggling in setting a 'Default Selected Value' Not sure if it should be an expression or it would be a constant value?

Could you please help?

**Comment by geck123** [comment] 2017-09-08 03:38
Another issue with 'Default Selected Value':

I entered a value for 'Default Selected Value'.  However, the drop-down list does not select the 'Default Selected Value' as default, as soon as I press "Done" with the Edit.  Instead, I need to refresh the page in order to show the 'Default Selected Value'.

Could you please fix this?  Thanks.

**Comment by balexbyrd** [comment] 2018-04-20 21:37
Closing as it's a duplicate of #8

**Closed by balexbyrd** 2018-04-20 21:37 UTC
