### ISSUE TITLE
Extension not working with June 2018

### ISSUE THREAD

**Issue by leematthewshome** [balexbyrd/sense-FieldUI#19] opened 2018-05-29 02:45 UTC
I am testing your extension with the latest Qlik Sense desktop (June 2018 preview) and the fields I have used in the past are not displaying. I get an "Invalid Visualization" error.

Just giving you a heads up on possible problems with the June release.

**Comment by Martin-Tenghagen** [comment] 2018-05-29 07:53
This extension imports the qlik module as js/qlik which is unsupported and will fail to render in June 2018 of Qlik Sense.

See: https://help.qlik.com/en-US/sense-developer/April2018/Subsystems/Extensions/Content/Howtos/call-qlik-library.htm

**Comment by RRKONDAVETI** [comment] 2018-06-27 10:55
Hi,

Would it be possible to update this extension to work with June 2018 ?

**Comment by balexbyrd** [comment] 2018-07-24 13:06
This is a duplicate of #18 which is closed. I just tested this again in Chrome / QS June 2018 and she works great. Please re-pull and try it again. Thanks!

**Closed as completed by balexbyrd** 2018-07-24 13:06 UTC
